from tkinter import *
import tkinter as tk
root = Tk()
root.title('Login App')
root.geometry('400x400')
frame = Frame(master=root, height=200, width=360, bg='#d0efff')
lbl_1 = Label(frame, text="Full Name", bg='#3895D3', fg='White', width=12 )
lbl_2 = Label(frame, text="Email Id", bg='#3895D3', fg='White', width=12 )
lbl_3 = Label(frame, text="Enter Password", bg='#3895D3', fg='White', width=12 )
name_entry = Entry(frame)
email_entry = Entry(frame)
pass_entry = Entry(frame, show="*")
def display():
    name = name_entry.get()
    greet = "Hey "+name
    message = "\nCongratulations for your new account"
    textbox.insert(END, greet)
    textbox.insert(END, message)
textbox = Text(bg='#BEBEBE', fg='Black')
btn = Button(text="Create account", command=display, bg='Red')
frame.place(x=20, y=0)
lbl_1.place(x=20, y=20)
name_entry.place(x=150, y=20)
lbl_2.place(x=20, y=80)
email_entry.place(x=150, y=80)
lbl_3.place(x=20, y=140)
pass_entry.place(x=150, y=140)
btn.place(x=130, y=210)
textbox.place(y=250)
root.mainloop()